# Generated by Django 5.2.8 on 2025-11-28 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('allowed_levels', models.ManyToManyField(related_name='fields', to='requests_app.classlevel', verbose_name='Niveaux autorisés')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='requests_app.field', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Axe',
                'verbose_name_plural': 'Axes',
                'unique_together': {('field', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien')),
                ('read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('student_name', models.CharField(max_length=200, verbose_name="Nom de l'étudiant")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('type', models.CharField(choices=[('cc', 'CC (Contrôle Continu)'), ('exam', 'EXAM (Examen)')], max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('received', 'Reçue'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('in_cellule', 'En cellule informatique'), ('returned', 'Retournée'), ('done', 'Terminée')], default='sent', max_length=20, verbose_name='Statut')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à')),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requests_app.axis', verbose_name='Axe')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests_app.classlevel', verbose_name='Niveau')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests_app.field', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('from_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut précédent')),
                ('to_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nouveau statut')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='requests_app.request', verbose_name='Requête')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/%Y/%m/%d/', verbose_name='Fichier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.request', verbose_name='Requête')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Acceptée'), ('rejected', 'Rejetée')], max_length=10, verbose_name='Statut')),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nouvelle note')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='requests_app.request', verbose_name='Requête')),
            ],
            options={
                'verbose_name': 'Résultat de requête',
                'verbose_name_plural': 'Résultats de requêtes',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests_app.classlevel', verbose_name='Niveau')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requests_app.field', verbose_name='Filière')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='requests_app.student', verbose_name='Étudiant'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('class_levels', models.ManyToManyField(related_name='subjects', to='requests_app.classlevel', verbose_name='Niveaux')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='requests_app.field', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests_app.subject', verbose_name='Matière'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False, verbose_name='Chef de département')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='requests_app.field', verbose_name='Filière (si HOD)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('subjects', models.ManyToManyField(blank=True, related_name='lecturers', to='requests_app.subject', verbose_name='Matières enseignées')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
    ]
