# Generated by Django 4.2.26 on 2025-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Note actuelle'),
        ),
    ]
