# Generated by Django 4.2.26 on 2025-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_request_current_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='cellule_informatique',
            field=models.BooleanField(default=False, verbose_name='Membre de la cellule informatique'),
        ),
    ]
